plugins {
    id 'fabric-loom'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir '../shared/src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
            srcDir '../shared/src/main/resources'
        }
    }
    test {
        java {
            srcDir 'src/test/java'
            srcDir '../shared/src/test/java'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    compileOnly "com.electronwill.night-config:core:3.8.3"
    compileOnly "com.electronwill.night-config:toml:3.8.3"

    testImplementation platform('org.junit:junit-bom:5.11.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "com.electronwill.night-config:core:3.8.3"
    testImplementation "com.electronwill.night-config:toml:3.8.3"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
